"""Python code generation engine for SQCanvas designs."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from sqcanvas.components.base import Component
from sqcanvas.utility.attr_dict import AttrDict

if TYPE_CHECKING:
    from sqcanvas.designs.design_base import Design


def _format_option_value(key: str, val: Any) -> Any:
    """Format an option value into a clean, canonical string or literal representation."""
    if isinstance(val, (int, float)):
        if key in ("orientation", "layer"):
            return f"{int(val)}" if (isinstance(val, int) or float(val).is_integer()) else f"{val:g}"
        return f"{val:g}um"
    return val


def _extract_delta_options(comp: Component) -> dict[str, Any]:
    """Extract positioning options and any properties differing from class defaults."""
    default_dict = AttrDict(Component.default_options)
    default_dict.update(getattr(comp.__class__, "default_options", {}))

    delta: dict[str, Any] = {}

    # 1. Always prioritize placement coordinates
    raw_pos_x = comp.options.get("pos_x", 0.0)
    raw_pos_y = comp.options.get("pos_y", 0.0)
    raw_orientation = comp.options.get("orientation", "0")

    delta["pos_x"] = _format_option_value("pos_x", raw_pos_x)
    delta["pos_y"] = _format_option_value("pos_y", raw_pos_y)

    str_ori = _format_option_value("orientation", raw_orientation)
    if str(str_ori) not in ("0", "0.0"):
        delta["orientation"] = str_ori

    # 2. Extract customized options
    for key, val in comp.options.items():
        if key in ("pos_x", "pos_y", "orientation"):
            continue
        # Skip internal or design-wide defaults unless modified
        if key in ("chip", "layer") and str(val) == str(default_dict.get(key, "")):
            continue

        default_val = default_dict.get(key)
        # Check if modified from default
        if default_val is None or str(val) != str(default_val):
            delta[key] = _format_option_value(key, val)

    return delta


def generate_python_script(design: Design) -> str:
    """Generate a clean, standalone, executable Python script from a SQCanvas Design."""
    design_cls_name = design.__class__.__name__

    # Collect component classes used
    used_classes: set[str] = set()
    components_list = design.get_components() if hasattr(design, "get_components") else list(design.components.values())

    for comp in components_list:
        used_classes.add(comp.__class__.__name__)

    # Build Header & Imports
    lines: list[str] = [
        '"""SQCanvas Superconducting Circuit Design Script.',
        "",
        "Auto-generated by SQCanvas CAD Studio.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f"from sqcanvas.designs import {design_cls_name}",
    ]

    if used_classes:
        sorted_classes = sorted(used_classes)
        if len(sorted_classes) == 1:
            lines.append(f"from sqcanvas.components import {sorted_classes[0]}")
        else:
            lines.append("from sqcanvas.components import (")
            for cls_name in sorted_classes:
                lines.append(f"    {cls_name},")
            lines.append(")")

    lines.append("")
    lines.append("")
    lines.append(f"def build_design() -> {design_cls_name}:")
    lines.append(f'    """Construct the {design_cls_name} layout and components."""')
    lines.append(f"    design = {design_cls_name}()")

    if not components_list:
        lines.append("    # Empty design canvas")
        lines.append("    return design")
    else:
        lines.append("")
        for comp in components_list:
            cls_name = comp.__class__.__name__
            name = comp.name
            delta_opts = _extract_delta_options(comp)

            lines.append(f"    {cls_name}(")
            lines.append("        design,")
            lines.append(f"        name={name!r},")
            lines.append("        options={")
            for k, v in delta_opts.items():
                if isinstance(v, str):
                    lines.append(f"            {k!r}: {v!r},")
                else:
                    lines.append(f"            {k!r}: {v},")
            lines.append("        },")
            lines.append("    )")
            lines.append("")

        lines.append("    return design")

    # Add standalone execution block
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    # Launch interactive CAD GUI viewer")
    lines.append("    design = build_design()")
    lines.append("    design.open_gui()")
    lines.append("")

    return "\n".join(lines)


def export_python_script(design: Design, filepath: str | Path) -> Path:
    """Save the design as a standalone Python script to the specified filepath."""
    target_path = Path(filepath).resolve()
    target_path.parent.mkdir(parents=True, exist_ok=True)
    code = generate_python_script(design)
    target_path.write_text(code, encoding="utf-8")
    return target_path
